version: "3.9"

services:
  client:
    build: .
    entrypoint: [ "./client", "CMakeLists.txt", "server", "8080" ]
    depends_on:
      - server
  server:
    build: .
    entrypoint: [ "./server", "8080" ]