version: "3.9"

services:
  client1:
    build: .
    entrypoint: [ "./client", "/app/CMakeLists.txt", "server", "8080" ]
    depends_on:
      - server
  client2:
    build: .
    entrypoint: [ "./client", "/app/CMakeLists.txt", "server", "8080" ]
    depends_on:
      - server
  client3:
    build: .
    entrypoint: [ "./client", "/app/CMakeLists.txt", "server", "8080" ]
    depends_on:
      - server
  client4:
    build: .
    entrypoint: [ "./client", "/app/server", "server", "8080" ]
    depends_on:
      - server
  server:
    build: .
    entrypoint: [ "./server", "8080" ]